upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 180
max_input_time = 180
memory_limit = 512M

log_errors = On
error_log = /var/log/php/error.log
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off

date.timezone = UTC

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1

[mail function]
sendmail_path = /usr/sbin/sendmail -t -i
