<?php
/**
 * WordPress Configuration for ABC Local Stack
 * Generated by the ABC_NEWS tooling.
 */

// Database
define( 'DB_NAME', getenv('WORDPRESS_DB_NAME') ?: 'abcnews' );
define( 'DB_USER', getenv('WORDPRESS_DB_USER') ?: 'abcnews' );
define( 'DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD') ?: 'abcnewspass' );
define( 'DB_HOST', getenv('WORDPRESS_DB_HOST') ?: 'mariadb' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', 'utf8mb4_unicode_ci' );

// Table prefix
$table_prefix = getenv('WORDPRESS_TABLE_PREFIX') ?: 'wp_';

// Site URLs — bind to the local host IP so cookies/resources work in browser
define( 'WP_HOME', 'http://192.168.1.78:8085' );
define( 'WP_SITEURL', 'http://192.168.1.78:8085' );

// Dev/debug
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
define( 'SCRIPT_DEBUG', true );
define( 'WP_DEBUG_LOG_PATH', '/var/log/php/wp-debug.log' );
@ini_set( 'log_errors', 'On' );
@ini_set( 'error_log', '/var/log/php/wp-errors.log' );

// Performance + behavior
define( 'WP_MEMORY_LIMIT', '512M' );
define( 'WP_MAX_MEMORY_LIMIT', '768M' );
define( 'WP_POST_REVISIONS', 10 );
define( 'AUTOSAVE_INTERVAL', 120 );
define( 'EMPTY_TRASH_DAYS', 7 );
define( 'MEDIA_TRASH', false );
define( 'WP_AUTO_UPDATE_CORE', false );

// Filesystem (allow direct writes for theme/plugin dev)
define( 'FS_METHOD', 'direct' );
define( 'FS_CHMOD_DIR', 0755 );
define( 'FS_CHMOD_FILE', 0644 );

// Security (dev defaults — DO NOT use in production)
define( 'FORCE_SSL_ADMIN', false );
define( 'DISALLOW_FILE_EDIT', false );

// Reverse-proxy/container awareness
if ( isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
    $_SERVER['HTTPS'] = 'on';
}
if ( ! empty($_SERVER['HTTP_X_FORWARDED_HOST']) ) {
    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}

// Absolute path to WordPress
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

// Sets up WordPress vars and included files
require_once ABSPATH . 'wp-settings.php';
